name: workflow timeout check
on:
  push:
    branches: "*"
  workflow_dispatch:
jobs:
  timeout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.2.2
      - name: run script
        run: |
          echo "Starting..."
          ls -lrt 
      - name: last step
        run: echo "Ending..."
