name: Testing workflow
on:
  push:
    branches: "*"
  workflow_dispatch:
jobs:
  timeout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.2.2
      - name: run script
        # timeout-minutes: 2
        continue-on-error: true
        run: |
          echo "Starting..."
          chmod +x script.sh
          ls -lrt 
          echo "$SHELL `whoami`"
          # ./script.sh
          echo RC: $?
      - name: Tmp checks
        run: |
          echo "Checking..."
          echo "SHELL: $SHELL"
          echo "USER: `whoami`"
          echo "PWD: `pwd`"
          echo "HOME: $HOME"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "$SHELL"
          echo "$USER"
          echo ${{ github.action }}
          echo ${{ github.actor }}
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.repositoryUrl }}
          echo ${{ github.run_number }}
          echo ${{ github.run_id }}
          echo ${{ github.run_attempt }}
          echo ${{ github.event }}
          echo ${{ github.event_name }}
          echo ${{ github.event_path }}
          echo "MOI=DKR" >> $GITHUB_ENV
      - name: Show variables
        run: |
          echo "Checking variables..."
          set -x
          echo "MOI: $MOI"
          echo $PATH
          mkdir /tmp/moidir
          touch /tmp/moidir/new.sh
          echo "/tmp/moidir/new.sh"
          echo "/tmp" >> $GITHUB_PATH
          echo $PATH
          which new.sh || ls -lrt 
      - name: last step
        run: echo "Ending..."
